package:
  name: enaml
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: https://github.com/nucleic/enaml.git
  git_tag: master
  patches:
    - setup.py.patch

build:
  number: 1
  entry_points:
    - enaml-run = enaml.runner:main
  osx_is_app: True

requirements:
  build:
    - python
    - atom
    - kiwisolver
    - ply
  run:
    - python
    - python.app       [osx]
    - atom
    - pyqt
    - kiwisolver
    - ply
    - future

test:
  commands:
    - enaml-run --help
  imports:
    - enaml
    - enaml.callableref
    - enaml.colorext
    - enaml.core.alias
    - enaml.core.dynamicscope
    - enaml.core.funchelper
    - enaml.fontext
    - enaml.signaling
    - enaml.weakmethod

about:
  home: https://github.com/nucleic/enaml
  license: BSD
  license_file: COPYING.txt
  summary: Declarative DSL for building rich user interfaces in Python
